{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncthing.fullname" . }}

{{- with $.Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
    
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}

{{- end }}