apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}-webui
  labels:
    app: {{ include "syncthing.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8384
      targetPort: 8384
      protocol: TCP
      name: http
  selector:
    app: {{ include "syncthing.name" . }}