apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}
  labels:
    app: {{ include "syncthing.name" . }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: tcp-file-transfer
      port: 22000
      targetPort: 22000
      protocol: TCP
      nodePort: {{ .Values.ports.tcpFileTransfer.nodePort }}

    - name: udp-file-transfer
      port: 22000
      targetPort: 22000
      protocol: UDP
      nodePort: {{ .Values.ports.udpFileTransfer.nodePort }}

  selector:
    app: {{ include "syncthing.name" . }}
